interface ZR_JOB_POSTING_INTF
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF ROOT,
 CREATE_ROOT                    TYPE /BOBF/ACT_KEY VALUE '000C293719C11EEF8A94D7ACB6AE12F0',
 DELETE_ROOT                    TYPE /BOBF/ACT_KEY VALUE '000C293719C11EEF8A94D7ACB6AE92F0',
 LOCK_ROOT                      TYPE /BOBF/ACT_KEY VALUE '000C293719C11EEF8A94D7ACB6AD52F0',
 SAVE_ROOT                      TYPE /BOBF/ACT_KEY VALUE '000C293719C11EEF8A94D7ACB6AF12F0',
 UNLOCK_ROOT                    TYPE /BOBF/ACT_KEY VALUE '000C293719C11EEF8A94D7ACB6AD92F0',
 UPDATE_ROOT                    TYPE /BOBF/ACT_KEY VALUE '000C293719C11EEF8A94D7ACB6AE52F0',
 VALIDATE_ROOT                  TYPE /BOBF/ACT_KEY VALUE '000C293719C11EEF8A94D7ACB6AED2F0',
      END OF ROOT,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF ROOT,
        BEGIN OF LOCK_ROOT,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF LOCK_ROOT,
        BEGIN OF UNLOCK_ROOT,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF UNLOCK_ROOT,
      END OF ROOT,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF ROOT,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C293719C11EEF8A94D7ACB6AD32F0',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C293719C11EEF8A94D7ACB6ACF2F0',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C293719C11EEF8A94D7ACB6ADF2F0',
      END OF ROOT,
      BEGIN OF ROOT_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C293719C11EEF8A94D7ACB6AF72F0',
      END OF ROOT_LOCK,
      BEGIN OF ROOT_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C293719C11EEF8A94D7ACB6AF52F0',
      END OF ROOT_MESSAGE,
      BEGIN OF ROOT_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '000C293719C11EEF8A94D7ACB6AF92F0',
      END OF ROOT_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF ROOT,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF ROOT,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '000C293719C11EEF8A94D7ACB6AC52F0' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'ZR_JOB_POSTING' .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 ROOT                           TYPE /BOBF/OBM_NODE_KEY VALUE '000C293719C11EEF8A94D7ACB6AC92F0',
 ROOT_LOCK                      TYPE /BOBF/OBM_NODE_KEY VALUE '000C293719C11EEF8A94D7ACB6AD12F0',
 ROOT_MESSAGE                   TYPE /BOBF/OBM_NODE_KEY VALUE '000C293719C11EEF8A94D7ACB6ACD2F0',
 ROOT_PROPERTY                  TYPE /BOBF/OBM_NODE_KEY VALUE '000C293719C11EEF8A94D7ACB6ADD2F0',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF ROOT,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  JOBPOSTING_ID                  TYPE STRING VALUE 'JOBPOSTING_ID',
  JOB_DESCRIPTION                TYPE STRING VALUE 'JOB_DESCRIPTION',
  JOB_COUNTRY                    TYPE STRING VALUE 'JOB_COUNTRY',
  JOB_CITY                       TYPE STRING VALUE 'JOB_CITY',
  JOB_TYPE                       TYPE STRING VALUE 'JOB_TYPE',
  JOB_CONTACT_NAME               TYPE STRING VALUE 'JOB_CONTACT_NAME',
  JOB_CONTACT_EMAIL              TYPE STRING VALUE 'JOB_CONTACT_EMAIL',
      END OF ROOT,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF ROOT,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '000C293719C11EEF8A94D7ACB6ACB2F0',
      END OF ROOT,
    END OF SC_NODE_CATEGORY .
  constants:
    BEGIN OF SC_QUERY,
      BEGIN OF ROOT,
 QUERY                          TYPE /BOBF/OBM_QUERY_KEY VALUE '000C293719C11EEF8D91BD6E6EDED32D',
      END OF ROOT,
    END OF SC_QUERY .
endinterface.
